// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozexruxmhazuubeikpdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96ZXhydXhtaGF6dXViZWlrcGR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMjc5MTksImV4cCI6MjA2MjkwMzkxOX0.lko7KF0MPCjVcVjw3v7Z1j-TXkPhaGB69oRfNeZs6Oo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);